//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoBackend.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REV
    {
        public int Rev_Id { get; set; }
        public string Prod_id { get; set; }
        public string User_ID { get; set; }
        public string Rev_text { get; set; }
    
        public virtual PROD PROD { get; set; }
        public virtual USER USER { get; set; }
    }
}
