//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoBackend.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVs
    {
        public int REV_ID { get; set; }
        public string PROD_ID { get; set; }
        public string USER_ID { get; set; }
        public string REV_text { get; set; }
    
        public virtual PRODs PROD { get; set; }
        public virtual USERs USER { get; set; }
    }
}
