//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoBackend.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSIONS
    {
        public int Sessions_ID { get; set; }
        public string Sessions_Token { get; set; }
        public string Sessions_TTL { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
