//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasusB2D3.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestModel1Container : DbContext
    {
        public TestModel1Container()
            : base("name=TestModel1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HAND_GEB> HAND_GEB { get; set; }
        public virtual DbSet<PROD> PRODs { get; set; }
        public virtual DbSet<HAND_SUB_GEB_PROD> HAND_SUB_GEB_PROD { get; set; }
        public virtual DbSet<SUB_BEG> SUB_BEG { get; set; }
        public virtual DbSet<REV> REVs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<CAT> CATs { get; set; }
        public virtual DbSet<CAT_PROD> CAT_PROD { get; set; }
    }
}
