//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasusB2D3.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAND_GEB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HAND_GEB()
        {
            this.HAND_SUB_GEB_PROD = new HashSet<HAND_SUB_GEB_PROD>();
        }
    
        public int Hand_ID { get; set; }
        public string Hand_Name { get; set; }
        public string Hand_IMG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAND_SUB_GEB_PROD> HAND_SUB_GEB_PROD { get; set; }
    }
}
