//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasusB2D3.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD()
        {
            this.HAND_SUB_GEB_PROD = new HashSet<HAND_SUB_GEB_PROD>();
            this.REVs = new HashSet<REV>();
            this.Entity1 = new HashSet<CAT_PROD>();
        }
    
        public int Prod_ID { get; set; }
        public string Prod_Name { get; set; }
        public System.DateTime Prod_Dat { get; set; }
        public string Prod_Size { get; set; }
        public string Prod_Weight { get; set; }
        public string Prod_Cost { get; set; }
        public Nullable<bool> Prod_Covered { get; set; }
        public string Prod_Avail { get; set; }
        public string Prod_Desc { get; set; }
        public string Prod_Spec { get; set; }
        public string Prod_Req { get; set; }
        public string Prod_Mov { get; set; }
        public Nullable<long> Prod_Views { get; set; }
        public string Prod_Validator { get; set; }
        public string Prod_Val_Dat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAND_SUB_GEB_PROD> HAND_SUB_GEB_PROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REV> REVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PROD> Entity1 { get; set; }
    }
}
